name: 'Setup Tech Stack'
description: 'Sets up the required tech stack based on app configuration'

inputs:
  app-dir:
    description: 'Directory of the application'
    required: true
  config-path:
    description: 'Path to the config.json file'
    required: true
    default: './config.json'

runs:
  using: 'composite'
  steps:
    - name: Read config
      id: config
      shell: bash
      run: |
        CONFIG=$(jq -c --arg app "${{ inputs.app-dir }}" '.apps[$app]' ${{ inputs.config-path }})
        echo "config=$CONFIG" >> $GITHUB_OUTPUT
        echo "type=$(echo "$CONFIG" | jq -r '.type')" >> $GITHUB_OUTPUT
        echo "version=$(echo "$CONFIG" | jq -r '.version')" >> $GITHUB_OUTPUT
        echo "install_command=$(echo "$CONFIG" | jq -r '.["install-command"]')" >> $GITHUB_OUTPUT
        echo "test_command=$(echo "$CONFIG" | jq -r '.["test-command"]')" >> $GITHUB_OUTPUT
        echo "build_command=$(echo "$CONFIG" | jq -r '.["build-command"]')" >> $GITHUB_OUTPUT
#Node dependency
    - name: Setup Node.js
      if: ${{ steps.config.outputs.type == 'node' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.config.outputs.version }}
        #cache: 'npm'
#
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: ${{ steps.config.outputs.install_command }}

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: ${{ steps.config.outputs.test_command }}
      continue-on-error: false

    - name: Build application
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: ${{ steps.config.outputs.build_command }}
